---
title: "Stacked bar plots"
author: "Palni Kundra"
date: "28/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Libraries
```{r, warning=FALSE, message=FALSE}
library(ComplexHeatmap)
library(ggplot2)
library(reshape2)
library(readxl)
library(seriation)
library(writexl)
library(plyr)
source("../figures/functions.R")
```


# Feces
```{r}
xl <- lapply(2:9, function(x) {
  a <- data.frame(read_xlsx(
    path = "feces_relative_abundance_all_donors.xlsx",
    sheet = x
  ))[-c(1), -c(4:5)]
  b <- a[, c(1, 4)]
  c <- split(b, b[, 1])
  d <- lapply(c, function(x) data.frame(Phylum = x[1, 1], Average = sum(x[, 2])))
  ldply(d, .id = NULL)
})

names(xl) <- paste0("D", 1:8)

data <- ldply(xl, .id = "Donor")

data$Average <- data$Average * 100

data$Average <- ifelse(test = data$Average >= 1, yes = data$Average, no = 0)

writexl::write_xlsx(x = data, path = "feces_corrected.xlsx", col_names = T, format_headers = T)

ds <- split(data, data$Phylum)

ds1 <- list()
for (i in 1:length(ds)) {
  a <- ds[[i]]$Average
  if (sum(a) != 0) {
    n <- names(ds[i])
    ds1[[n]] <- data.frame(Donor = paste0("D", 1:8), Phylum = n, Average = ds[[i]]$Average)
  }
}

tab <- ldply(ds1, .id = NULL)
```

## Plot
```{r}
colours = rcartocolor::carto_pal(n = 12, name = "Safe")[c(1,3,4,5,10,8,12)]
names(colours) <- c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria", "Desulfobacterota", "Euryarchaeota", "Verrucomicrobiota")

a <- ggplot(tab, aes(x = Donor, fill = Phylum, y = Average)) +
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 0, size = 12, colour = "black", vjust = 0.5, hjust = 0.5, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 12, colour = "black"),
    axis.text.y = element_text(colour = "black", size = 12, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "", y = "Relative Abundance (%)", fill = "Phylum") +
  scale_fill_manual(values = colours[unique(tab$Phylum)])
  # scale_fill_carto_d()

ag <- gridExtra::grid.arrange(egg::set_panel_size(p = a, width = unit(6, "cm"), height = unit(6, "cm")))
ggsave(plot = ag, filename = "feces.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag, filename = "feces.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```


# Donors
```{r}
re <- lapply(2:9, function(x) {
  a <- data.frame(read_xlsx(
    path = "ASV table_Relative abundance_Rarefied data_treatments.xlsx",
    sheet = x
  ))[-c(1), -c(4:6,8:10,12:14,16:18)]
  b <- a[, c(1, 4:7)]
  c <- split(b, b[, 1])
  d <- lapply(c, function(x) data.frame(Phylum = x[1, 1], 
                                        Control = sum(x[, 2]),
                                        LB9NB12 = sum(x[, 3]),
                                        ExtraB9 = sum(x[, 4]),
                                        ExtraB12 = sum(x[, 5])))
  
  ldply(d, .id = NULL)
})

names(re) <- paste0("D", 1:8)

data <- ldply(re, .id = "Donor")

data[,3:6] <- data[,3:6] * 100

data$Control <- ifelse(test = data$Control >= 1, yes = data$Control, no = 0)
data$LB9NB12 <- ifelse(test = data$LB9NB12 >= 1, yes = data$LB9NB12, no = 0)
data$ExtraB9 <- ifelse(test = data$ExtraB9 >= 1, yes = data$ExtraB9, no = 0)
data$ExtraB12 <- ifelse(test = data$ExtraB12 >= 1, yes = data$ExtraB12, no = 0)

writexl::write_xlsx(x = data, path = "donor_corrected.xlsx", col_names = T, format_headers = T)

tab1 <- data%>%filter(rowSums(across(where(is.numeric)))!=0)

tab1 <- melt(tab1)
```

## Plot
```{r}
b <- ggplot(tab1, aes(x = variable, fill = Phylum, y = value)) +
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, size = 12, colour = "black", vjust = 0.5, hjust = 0.5, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 12, colour = "black"),
    axis.text.y = element_text(colour = "black", size = 12, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "", y = "Relative Abundance (%)", fill = "Phylum") +
scale_fill_manual(values = colours[unique(tab1$Phylum)]) +
  # scale_fill_carto_d() +
  facet_wrap(~Donor, nrow = 2) +
  theme(strip.background =element_rect(fill="white"))+
  theme(strip.text = element_text(colour = 'black', face = "bold", size = 12))

bg <- gridExtra::grid.arrange(egg::set_panel_size(p = b, width = unit(5, "cm"), height = unit(5, "cm")))
ggsave(plot = bg, filename = "donor.pdf", width = unit(11, "in"), height = unit(8.5, "in"), dpi = 320)
ggsave(plot = bg, filename = "donor.png", width = unit(11, "in"), height = unit(8.5, "in"), dpi = 320)
```




# 07.04.2022
```{r}
nd <- data.frame(
  read_xls(
    path = "Copy of Supplmentary_fig_1_donors.xls",
    sheet = 1
), check.names = F)

nd <- data.frame(t(nd))
nd <- nd[-1,]
colnames(nd) <- as.character(nd[nrow(nd) - 3,])
nd <- nd[-c((nrow(nd) - 3):nrow(nd)) ,]
row.names(nd) <- c(row.names(nd)[1:15], 
                   "Oscillospiraceae;Unknown", 
                   row.names(nd)[17:18],
                   "Ruminococcaceae;Unknown",
                   row.names(nd)[20:nrow(nd)])

writexl::write_xlsx(x = nd, path = "20220407_feces_new_data_corrected.xlsx", col_names = T, format_headers = T)

nd <- data.matrix(nd)

nd <- (nd/colSums(nd))

# tab2 <- data.frame(t(nd), check.names = F)
tab2 <- data.frame(nd)
tab2$Species <- rownames(tab2)
# tab2 <- melt(tab2)

tab2 %>%
  gather(Donor, Feces, -Species) -> tab3
```

## Plot
```{r}
colours = rcartocolor::carto_pal(n = 12, name = "Safe")[c(1,3,4,5,10,8,12)]
names(colours) <- c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria", "Desulfobacterota", "Euryarchaeota", "Verrucomicrobiota")

a <- ggplot(tab3, aes(x = Donor, fill = Species, y = Feces)) +
  geom_bar(stat = "identity", colour = "black") +
  theme_bw() +
  theme(legend.position = "none")
  theme(
    axis.text.x = element_text(angle = 0, size = 12, colour = "black", vjust = 0.5, hjust = 0.5, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 12, colour = "black"),
    axis.text.y = element_text(colour = "black", size = 12, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "", y = "Relative Abundance (%)", fill = "Phylum") +
  theme(legend.position = "none")
  scale_fill_manual(values = colours[unique(tab$Phylum)])
  # scale_fill_carto_d()

ag <- gridExtra::grid.arrange(egg::set_panel_size(p = a, width = unit(6, "cm"), height = unit(6, "cm")))
ggsave(plot = ag, filename = "feces.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag, filename = "feces.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)






Heatmap(nd, col = c("white", "red"), cluster_columns = F, name = "Percentage", row_names_gp = gpar(fontsize = 6))
```