---
title: "Palni"
author: "Deepak Tanwar"
date: "2/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Libraries
```{r, warning=FALSE, message=FALSE}
library(ComplexHeatmap)
library(ggplot2)
library(reshape2)
library(readxl)
library(seriation)
library(writexl)
library(plyr)
source("functions.R")

seriate_mat <- function(mat) {
  mat[is.na(mat)] <- 0
  mat[is.nan(mat)] <- 0
  mat[is.infinite(mat)] <- 0
  o <- seriate(max(mat) - mat, method = "PCA")
  mat <- mat[get_order(o, 1), ]
  mat <- mat[, get_order(o, 2)]
  return(mat)
}
```


# Data
```{r}
# NB9B12vsExtraB9
diff1 <- data.frame(
  read_xlsx(
    path = "DESeq_analysis_comparing_vs_NB9B12_Genus_level_analysis_donor_2_to_9.xlsx",
    sheet = 1, skip = 13
  )
)

diff1 <- diff1[complete.cases(diff1), ]
diff1 <- diff1[diff1$Genus != "Genus", ]
diff1 <- diff1[diff1$Genus != "-", ]
diff1$Comparison <- "ExtraB9 vs NB9B12"


# NB9B12vsExtraB12
diff2 <- data.frame(
  read_xlsx(
    path = "DESeq_analysis_comparing_vs_NB9B12_Genus_level_analysis_donor_2_to_9.xlsx",
    sheet = 2, skip = 10
  )
)

diff2 <- diff2[complete.cases(diff2), ]
diff2 <- diff2[diff2$Genus != "Genus", ]
diff2 <- diff2[diff2$Genus != "-", ]
diff2$Comparison <- "ExtraB12 vs NB9B12"

diff <- rbind(diff1, diff2)
diff$log2FoldChange <- round(as.numeric(diff$log2FoldChange), digits = 2)
diff$pvalue <- as.numeric(diff$pvalue)
diff$Donor <- gsub(pattern = "Donor ", replacement = "", x = diff$Donor)
diff[nrow(diff) + 1, ] <- NA
diff$Donor[nrow(diff)] <- "2"
diff$Comparison[nrow(diff)] <- "ExtraB12 vs NB9B12"
diff$Genus[nrow(diff)] <- "Roseburia"
diff[nrow(diff) + 1, ] <- NA
diff$Donor[nrow(diff)] <- "4"
diff$Comparison[nrow(diff)] <- "ExtraB9 vs NB9B12"
diff$Genus[nrow(diff)] <- "Roseburia"

diff$Donor <- as.numeric(diff$Donor) - 1
diff$Donor <- paste0("D", diff$Donor)

scfa <- data.frame(
  read_xlsx(path = "SCFAs_donor_1_to_9_concentration_in_mM.xlsx", sheet = 1),
  check.names = F
)
```

# Differential analysis Dot plot
```{r}
a <- ggplot(data = diff, mapping = aes(
  x = Donor,
  y = Genus,
  color = log2FoldChange,
  size = -log10(pvalue)
)) +
  geom_point(show.legend = T, alpha = 0.8, stroke = 1.5) +
  facet_wrap(~Comparison) +
  scale_colour_gradient2(low = "#313695", mid = "grey", high = "#A50026", limits = c(floor(min(diff$log2FoldChange)), ceiling(max(diff$log2FoldChange))), breaks = c(-3, 0, 5.5)) +
  scale_size_continuous(breaks = c(10, 50)) +
  xlab("") +
  ylab("") +
  theme_bw(base_family = "Helvetica") +
  th +
  guides(
    size = guide_legend(
      title.position = "left",
      title.hjust = 0.5,
      title.vjust = 0.5,
      nrow = 1, size = 10,
      label.hjust = 0.5, label.vjust = 0.5,
      order = 2
    ),
    colour = guide_colorbar(
      nrow = 1, order = 1,
      title.position = "left", title.hjust = 0.5, title.vjust = 1,
      barwidth = unit(2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 0.5, size = 10
    )
  ) +
  labs(
    size = expression(-Log[10] ~ italic(P) ~ " "),
    color = expression(Log[2] ~ "fold-change")
  ) +
  theme(axis.text.y = element_text(lineheight = 0.8), legend.spacing = unit(1, "cm"))


ag <- gridExtra::grid.arrange(egg::set_panel_size(p = a, width = unit(4, "cm"), height = unit(12, "cm")))
ggsave(plot = ag, filename = "diff.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag, filename = "diff.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```


# SCFA test
```{r}
scfa <- data.frame(
  read_xlsx(path = "SCFAs_donor_1_to_9_concentration_in_mM.xlsx", sheet = 1),
  check.names = F
)

scfa <- scfa[, -c(3:5)]

scfa <- scfa[, 1:11]

scfa$Donor <- gsub(pattern = "Donor ", replacement = "", x = scfa$Donor)
scfa$Donor <- as.numeric(scfa$Donor) - 1
scfa$Donor <- paste0("D", scfa$Donor)
scfa$Treatment <- gsub(pattern = " ", replacement = "", x = scfa$Treatment)
scfa$Treatment <- paste(scfa$Treatment, rep(1:3, 32), sep = "_")

scfa <- reshape2::melt(scfa)
n <- unique(scfa$Donor)

scfa <- split(scfa, scfa$Donor)
names(scfa) <- n

scfa_1 <- lapply(scfa, function(x) {
  a <- dcast(x, variable~Treatment)
  rownames(a) <- a[,1]
  a <- a[,-1]
  return(a)
  })

test_scfa <- lapply(scfa_1, function(x){
  # x <- scfa_1[[2]]
  b12 <- vector()
  
  for(i in 1:nrow(x)){
    b12 <- c(b12, wilcox.test(y = as.numeric(x[i,1:3]), x = as.numeric(x[i,4:6]), exact = FALSE)$p.value)
  }
  names(b12) <- rownames(x)
  
  
  b9 <- vector()
  
  for(i in 1:nrow(x)){
    b9 <- c(b9, wilcox.test(y = as.numeric(x[i,1:3]), x = as.numeric(x[i,7:9]), exact = FALSE)$p.value)
  }
  names(b9) <- rownames(x)
  
  
  nb <- vector()
  
  for(i in 1:nrow(x)){
    nb <- c(nb, wilcox.test(y = as.numeric(x[i,1:3]), x = as.numeric(x[i,10:12]), exact = FALSE)$p.value)
  }
  names(nb) <- rownames(x)
  
  
  data.frame(NB9B12 = nb, ExtraB9 = b9, ExtraB12 = b12)
  
})

res <- do.call(rbind, (test_scfa))


res <- data.frame(Donor =substr(x = rownames(res), start = 1, stop = 2),
                  Metabolites = gsub(pattern = ".*\\.", replacement = "", x = rownames(res)),
                  res
)

writexl::write_xlsx(x = res, path = "wilcoxon_test.xlsx", col_names = T, format_headers = T)


test_scfa1 <- lapply(scfa_1, function(x){
  x <- scfa_1[[2]]
  b12 <- vector()
  
  for(i in 1:nrow(x)){
    b12 <- c(b12, kruskal.test(as.numeric(x[i,1:3]), as.numeric(x[i,4:6]), exact = FALSE)$p.value)
  }
  names(b12) <- rownames(x)
  
  
  b9 <- vector()
  
  for(i in 1:nrow(x)){
    b9 <- c(b9, kruskal.test(as.numeric(x[i,1:3]), as.numeric(x[i,7:9]), exact = FALSE)$p.value)
  }
  names(b9) <- rownames(x)
  
  
  nb <- vector()
  
  for(i in 1:nrow(x)){
    nb <- c(nb, kruskal.test(as.numeric(x[i,1:3]), as.numeric(x[i,10:12]), exact = FALSE)$p.value)
  }
  names(nb) <- rownames(x)
  
  
  data.frame(NB9B12 = nb, ExtraB9 = b9, ExtraB12 = b12)
  
})

res <- do.call(rbind, (test_scfa))


res <- data.frame(Donor =substr(x = rownames(res), start = 1, stop = 2),
                  Metabolites = gsub(pattern = ".*\\.", replacement = "", x = rownames(res)),
                  res
)

```

# SCFA heatmap
```{r}
scfa <- data.frame(
  read_xlsx(path = "SCFAs_donor_1_to_9_concentration_in_mM.xlsx", sheet = 1),
  check.names = F
)

scfa <- scfa[, -c(3:5)]

scfa <- aggregate(scfa[, 3:11], list(Donor = scfa$Donor, Treatment = scfa$Treatment), mean)

scfa$Donor <- gsub(pattern = "Donor ", replacement = "", x = scfa$Donor)
scfa$Donor <- as.numeric(scfa$Donor) - 1
scfa$Donor <- paste0("D", scfa$Donor)
scfa$Treatment <- gsub(pattern = " ", replacement = "", x = scfa$Treatment)

scfa$ID <- paste(scfa$Donor, scfa$Treatment, sep = "_")

an <- scfa[, c(12, 1:2)]

rownames(scfa) <- scfa$ID
scfa <- scfa[, -c(12, 1:2)]
colnames(scfa) <- gsub(pattern = "\\ \\[mM]", replacement = "", x = colnames(scfa))

scfa1 <- split(x = scfa, f = gsub(pattern = "_.*", replacement = "", x = rownames(scfa)))
scfa1 <- lapply(scfa1, function(x) {
  a <- t(x)
  b <- data.matrix(a - a[, grep(pattern = "Control", x = colnames(a), value = F)])
  b <- t(b)
  b <- data.frame(ID = rownames(b), b)
  return(b)
})

scfa1 <- ldply(scfa1, data.frame, .id = NULL)
rownames(scfa1) <- scfa1$ID
scfa1 <- scfa1[, -1]
scfa1 <- t(scfa1)
scfa1 <- seriate_mat(mat = scfa1)

scfa2 <- split(x = scfa, f = gsub(pattern = "_.*", replacement = "", x = rownames(scfa)))

scfa2 <- lapply(scfa2, function(x) {
  a <- t(x)
  a <- a[, grep(pattern = "Control", x = colnames(a), invert = T)]
  b <- data.matrix(a - a[, grep(pattern = "NB9B12", x = colnames(a), value = F)])
  b <- t(b)
  b <- data.frame(ID = rownames(b), b)
  return(b)
})

scfa2 <- ldply(scfa2, data.frame, .id = NULL)
rownames(scfa2) <- scfa2$ID
scfa2 <- scfa2[, -1]
scfa2 <- t(scfa2)
scfa2 <- seriate_mat(mat = scfa2)
```

## Heatmaps (Control)
```{r}
rownames(an) <- an$ID
an$Treatment[an$Treatment == "NB9B12"] <- "LB9NB12"
an$Treatment <- factor(an$Treatment, levels = unique(an$Treatment)[c(1, 4, 3, 2)])
an <- an[c(grep(pattern = "Control", rownames(an)), 
           grep(pattern = "NB9B12", rownames(an)),
           grep(pattern = "ExtraB9", rownames(an)),
           grep(pattern = "ExtraB12", rownames(an))),]


rn <- rownames(scfa1)
rn <- rn[c(1,5,2,4,9,8,7,6,3)]

library(circlize)
col_fun <- colorRamp2(c(-5, 0, 5), c("blue", "white", "red"))
# cl <- col_fun(seq(-5, 5))

cols <- RColorBrewer::brewer.pal(n = 6, name = "Dark2")[c(1,2,3,6)]
names(cols) <- unique(an$Treatment)



set.seed(1)
h1 <- Heatmap(
  matrix = scfa1[rn, rownames(an)],
  col = col_fun,
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  show_row_names = T,
  show_column_names = F,
  name = "mM",
  # row_split = rd$Biotype,
  column_split = an[, 2, drop = FALSE],
  cluster_column_slices = F,
  show_parent_dend_line = FALSE,
  row_title_rot = 0,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  row_title_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  # column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    df = an[, 3, drop = F],
    col = list(Treatment = cols),
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    annotation_name_side = "right",
    # title = expression(Log[2] ~ "CPM"),
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 4, units = "cm"), width = unit(x = 9, units = "cm"),
  heatmap_legend_param = list(
    at = c(-5, 0, 5),
    # title = expression(Log[2] ~ "FC (mM)"),
    title = "Fold-change (mM)",
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)

pdf(file = "c.pdf", width = 11, height = 8.5)
draw(
  object = h1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

png(filename = "c.png", width = 11, height = 8.5, units = "in",res = 300)
draw(
  object = h1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()

jpeg(filename = "c.jpeg", width = 11, height = 8.5, units = "in",res = 300)
draw(
  object = h1,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()
```

## Heatmaps (N)
```{r}
an1 <- an[an$Treatment != "Control", ]
an1$Treatment <- factor(an1$Treatment, levels = unique(an1$Treatment)[c(3, 2, 1)])

an1 <- an1[rev(rownames(an1)), ]

library(circlize)
col_fun <- colorRamp2(c(-5, 0, 5), c("blue", "white", "red"))

set.seed(1)
h2 <- Heatmap(
  matrix = scfa2[, rownames(an1)],
  col = col_fun,
  cluster_rows = F,
  row_names_side = "left",
  cluster_columns = F,
  show_row_names = T,
  show_column_names = F,
  name = "mM",
  # row_split = rd$Biotype,
  column_split = an1[, 2, drop = FALSE],
  cluster_column_slices = F,
  show_parent_dend_line = FALSE,
  row_title_rot = 0,
  # row_title = NULL,
  row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  column_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  row_title_gp = gpar(fontsize = 8, fontfamily = "Helvetica"),
  # column_title = NULL,
  column_dend_height = unit(0.5, "cm"),
  use_raster = FALSE,
  top_annotation = HeatmapAnnotation(
    df = an1[, 3, drop = F],
    col = list(Group = cols[1:2]),
    simple_anno_size = unit(3, "mm"),
    show_annotation_name = TRUE,
    annotation_name_side = "right",
    # title = expression(Log[2] ~ "CPM"),
    annotation_name_rot = 0,
    annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"),
    annotation_legend_param = list(
      title_gp = gpar(fontsize = 10, fontface = "plain", fontfamily = "Helvetica"),
      labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
    )
  ),
  height = unit(x = 4, units = "cm"), width = unit(x = 9, units = "cm"),
  heatmap_legend_param = list(
    at = c(-5, 0, 5),
    # title = expression(Log[2] ~ "FC (mM)"),
    title = "Fold-change (mM)",
    legend_height = unit(1, "cm"),
    # title_position = "leftcenter-rot",
    title_gp = gpar(fontsize = 10, fontfamily = "Helvetica"),
    labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica")
  )
)


pdf(file = "n.pdf", width = 11, height = 8.5)
draw(
  object = h2,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE,
  align_annotation_legend = ""
)
dev.off()
```



# Differential analysis edgeR
```{r}
files <- list.files(path = "../diff_analysis", pattern = "xlsx", full.names = T)[-1]
names(files) <- gsub(pattern = "\\.xlsx", replacement = "", x = basename(files))
dea <- lapply(files, function(x){
  sh <- readxl::excel_sheets(x)
  ll <- lapply(sh, function(y) data.frame(read_xlsx(x, sheet = y)))
  names(ll) <- sh
  return(ll)
})

dea <- lapply(dea, function(x) ldply(x, data.frame, .id = "Comparison"))
dea <- ldply(dea, data.frame, .id = "Donor")

# dea <- melt(dea)
dea$ID <- paste(dea$Kingdom, dea$Phylum, dea$Class, dea$Order, dea$Family, dea$Genus, dea$Species, dea$OTU, sep = "|")

res <- dea
dea <- res[abs(res$logFC) >= 1 & res$P.Value <= 0.001,]
```

## dot plot
```{r}
dea1 <- dea[grep(pattern = "Control", x = dea$Comparison),]

b1 <- ggplot(data = dea1, mapping = aes(
  x = Donor,
  y = ID,
  color = logFC,
  size = -log10(P.Value)
)) +
  geom_point(show.legend = T, alpha = 0.7, stroke = 1.5) +
  facet_wrap(~Comparison, nrow = 1) +
  scale_colour_gradient2(low = "#313695", mid = "grey", high = "#A50026", limits = c(floor(min(dea1$logFC)), ceiling(max(dea1$logFC))), breaks = c(-6, 0, 6)) +
  scale_size_continuous(breaks = c(4, 9)) +
  xlab("") +
  ylab("") +
  theme_bw(base_family = "Helvetica") +
  th +
  guides(
    size = guide_legend(
      title.position = "left",
      title.hjust = 0.5,
      title.vjust = 0.5,
      nrow = 1, size = 10,
      label.hjust = 0.5, label.vjust = 0.5,
      order = 2
    ),
    colour = guide_colorbar(
      nrow = 1, order = 1,
      title.position = "left", title.hjust = 0.5, title.vjust = 1,
      barwidth = unit(2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 0.5, size = 10
    )
  ) +
  labs(
    size = expression(-Log[10] ~ italic(P) ~ " "),
    color = expression(Log[2] ~ "fold-change")
  ) +
  theme(axis.text.y = element_text(lineheight = 0.8), legend.spacing = unit(1, "cm"))


b1g <- gridExtra::grid.arrange(egg::set_panel_size(p = b1, width = unit(4, "cm"), height = unit(10, "in")))
ggsave(plot = b1g, filename = "diffc.pdf", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)
ggsave(plot = b1g, filename = "diffc.png", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)

ggsave(plot = b1g, filename = "diffc.jpeg", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)

ggsave(plot = b1g, filename = "diffc.svg", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)
```


```{r}
dea2 <- dea[grep(pattern = "Control", x = dea$Comparison, invert = T),]

b2 <- ggplot(data = dea2, mapping = aes(
  x = Donor,
  y = ID,
  color = logFC,
  size = -log10(P.Value)
)) +
  geom_point(show.legend = T, alpha = 0.7, stroke = 1.5) +
  facet_wrap(~Comparison, nrow = 1) +
  scale_colour_gradient2(low = "#313695", mid = "grey", high = "#A50026", limits = c(floor(min(dea2$logFC)), ceiling(max(dea2$logFC))), breaks = c(-6, 0, 6)) +
  scale_size_continuous(breaks = c(4, 7)) +
  xlab("") +
  ylab("") +
  theme_bw(base_family = "Helvetica") +
  th +
  guides(
    size = guide_legend(
      title.position = "left",
      title.hjust = 0.5,
      title.vjust = 0.5,
      nrow = 1, size = 10,
      label.hjust = 0.5, label.vjust = 0.5,
      order = 2
    ),
    colour = guide_colorbar(
      nrow = 1, order = 1,
      title.position = "left", title.hjust = 0.5, title.vjust = 1,
      barwidth = unit(2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 0.5, size = 10
    )
  ) +
  labs(
    size = expression(-Log[10] ~ italic(P) ~ " "),
    color = expression(Log[2] ~ "fold-change")
  ) +
  theme(axis.text.y = element_text(lineheight = 0.8), legend.spacing = unit(1, "cm"))

b2g <- gridExtra::grid.arrange(egg::set_panel_size(p = b2, width = unit(4, "cm"), height = unit(6, "in")))
ggsave(plot = b2g, filename = "diffn.pdf", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)

ggsave(plot = b2g, filename = "diffn.png", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)

ggsave(plot = b2g, filename = "diffn.jpeg", width = unit(13, "in"), height = unit(16.5, "in"), dpi = 320)
```