---
title: "Palni"
author: "Deepak Tanwar"
date: "2/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Libraries
```{r, warning=FALSE, message=FALSE}
library(ComplexHeatmap)
library(ggplot2)
library(reshape2)
library(readxl)
library(writexl)
library(plyr)
library(edgeR)
source("../figures/functions.R")

seriate_mat <- function(mat) {
  mat[is.na(mat)] <- 0
  mat[is.nan(mat)] <- 0
  mat[is.infinite(mat)] <- 0
  o <- seriate(max(mat) - mat, method = "PCA")
  mat <- mat[get_order(o, 1), ]
  mat <- mat[, get_order(o, 2)]
  return(mat)
}
```


# Data
```{r}
data <- lapply(2:9, function(x) {
  tab <- data.frame(read_xlsx("ASV_table_donor_2_to_9.xlsx", sheet = x, skip = 1), check.names = F)
  colnames(tab)[1] <- "OTU"
  colnames(tab)[2:8] <- tab[1, 2:8]
  tab <- tab[-1, -c(9:10)]
  colnames(tab) <- gsub(pattern = "Extra ", replacement = "Extra", x = colnames(tab))
  colnames(tab) <- gsub(pattern = " ", replacement = "_", x = colnames(tab))
  # d <- paste0("D", x - 1)
  # colnames(tab)[9:20] <- paste(d, colnames(tab)[9:20], sep = "_")
  return(tab)
})

names(data) <- paste0("D", 1:length(data))
#
# data <- Reduce(f = merge, x = data)
#
# meta <- data.frame(Samples = colnames(data)[9:20])
# # meta$Donor <-
```

# Differential analysis
```{r}
diff_analysis <- function(tab, cd, cr) {
  design <- model.matrix(~ 0 + group, data = cd)
  colnames(design) <- gsub(pattern = "group", replacement = "", x = colnames(design))

  y <- DGEList(counts = data.matrix(tab), samples = cd)

  keep <- filterByExpr(y, design = design, min.count = 10)

  y <- y[keep, ]

  dds <- calcNormFactors(y)
  v <- voom(dds, design = design)
  contrast.matrix <- makeContrasts(contrasts = cr, levels = design)
  fit <- lmFit(v)
  fit2 <- contrasts.fit(fit, contrast.matrix)
  fit2 <- eBayes(fit2)

  ta <- as.data.frame(topTable(fit2, coef = 1, number = Inf))
  ta <- data.frame(OTU = rownames(ta), ta, stringsAsFactors = F)
  return(ta)
}

colData <- data.frame(samples = colnames(data[[1]])[9:20])
colData$samples <- gsub(pattern = "D[0-9]_", replacement = "", x = colData$samples)
colData$group <- gsub(pattern = "_.*", replacement = "", x = colData$samples)
rownames(colData) <- colData$samples

rd <- data[[1]][,1:8]

dea <- lapply(data, function(x) {
  # x <- data[[2]]
  rownames(x) <- x$OTU
  a <- diff_analysis(
    tab = x[, grep(pattern = "Control|NB9B12", x = colnames(x))],
    cd = colData[grep(pattern = "Control|NB9B12", x = rownames(colData)), ],
    cr = "NB9B12-Control"
  )
  a <- merge(rd,a)
  
  b <- diff_analysis(
    tab = x[, grep(pattern = "Control|ExtraB9", x = colnames(x))],
    cd = colData[grep(pattern = "Control|ExtraB9", x = rownames(colData)), ],
    cr = "ExtraB9-Control"
  )
  b <- merge(rd,b)
  
  c <- diff_analysis(
    tab = x[, grep(pattern = "Control|ExtraB12", x = colnames(x))],
    cd = colData[grep(pattern = "Control|ExtraB12", x = rownames(colData)), ],
    cr = "ExtraB12-Control"
  )
  c <- merge(rd,c)
  
  d <- diff_analysis(
    tab = x[, grep(pattern = "NB9B12|ExtraB9", x = colnames(x))],
    cd = colData[grep(pattern = "NB9B12|ExtraB9", x = rownames(colData)), ],
    cr = "ExtraB9-NB9B12"
  )
  d <- merge(rd,d)
  
  e <- diff_analysis(
    tab = x[, grep(pattern = "NB9B12|ExtraB12", x = colnames(x))],
    cd = colData[grep(pattern = "NB9B12|ExtraB12", x = rownames(colData)), ],
    cr = "ExtraB12-NB9B12"
  )
  e <- merge(rd,e)
  
  ll <- list(
    NB9B12vsControl = a,
    ExtraB9vsControl = b,
    ExtraB12vsControl = c,
    ExtraB9vsNB9B12 = d,
    ExtraB12vsNB9B12 = e
  )
  
  return(ll)
})
```

# Save tables
```{r}
for(i in seq_along(dea)){
  write_xlsx(x = dea[[i]], path = paste0(names(dea)[i], ".xlsx"), format_headers = T)  
}

```