---
title: "Palni"
author: "Palni Kundra"
date: "14.07.2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Libraries
```{r, warning=FALSE, message=FALSE}
library(ComplexHeatmap)
library(ggplot2)
library(reshape2)
library(readxl)
library(seriation)
library(writexl)
library(plyr)
source("../figures/functions.R")

seriate_mat <- function(mat) {
  mat[is.na(mat)] <- 0
  mat[is.nan(mat)] <- 0
  mat[is.infinite(mat)] <- 0
  o <- seriate(max(mat) - mat, method = "PCA")
  mat <- mat[get_order(o, 1), ]
  mat <- mat[, get_order(o, 2)]
  return(mat)
}
```


# Data
```{r}
data <- data.frame(
  read_xlsx(
    path = "B12_content_all_donor.xlsx"
  )
)

colnames(data)[c(2, 5)] <- c("TimePoint", "B12_ng_ml")
data$ID <- paste(data$Treatment, data$Replicate, data$Donor, sep = "_")


t0 <- data[data$TimePoint == "0", 5:6]
colnames(t0)[1] <- "T0"

t24 <- data[data$TimePoint == 24, 5:6]
colnames(t24)[1] <- "T24"

diff <- merge(t0, t24)
diff$delta <- diff$T24 - diff$T0

ann <- data[, c(1, 3, 4, 6)]
ann <- ann[!duplicated(ann), ]
diff <- merge(ann, diff)



data_summary <- function(data, varname, groupnames) {
  require(plyr)
  summary_func <- function(x, col) {
    c(
      mean = mean(x[[col]], na.rm = TRUE),
      sd = sd(x[[col]], na.rm = TRUE)
    )
  }
  data_sum <- ddply(data, groupnames,
    .fun = summary_func,
    varname
  )
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}


ds <- data_summary(data = diff, varname = "delta", groupnames = c("Treatment", "Donor"))
ds$Treatment <- factor(ds$Treatment, unique(ds$Treatment)[c(1, 3, 2)])

ds$lim <- ifelse(test = ds$delta < 0, yes = ds$delta - ds$sd, no = ds$delta + ds$sd)
```

# Differential analysis Dot plot
```{r}
a <- ggplot(data = ds, mapping = aes(
  x = Donor,
  y = delta,
  fill = Treatment
)) +
  theme_bw(base_family = "Helvetica") +
  geom_bar(
    stat = "identity", color = "black",
    position = position_dodge(.9)
  ) +
  geom_errorbar(aes(ymin = delta, ymax = lim),
    width = 0.5,
    position = position_dodge(.9)
  ) +
  xlab("") +
  ylab(expression(Delta ~ Concentration ~ (ng / ml))) +
  scale_y_continuous(limits = c(-1000, 1000), breaks = seq(-1000, 1000, len = 11)) +
  theme(
    legend.key.height = unit(0.3, "cm"), # change legend key height
    legend.key.width = unit(0.3, "cm")
  )




ag <- gridExtra::grid.arrange(egg::set_panel_size(p = a, width = unit(8, "cm"), height = unit(6, "cm")))
ggsave(plot = ag, filename = "diff.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
ggsave(plot = ag, filename = "diff.png", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```
